app = "homebridge-app"
primary_region = "lax"  # Los Angeles region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[http_service.ports]]
  port = 443
  handlers = ["tls", "http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 